### ISSUE TITLE
При нажатті на головну іконку нічого не відбувається

### ISSUE THREAD

**Issue by Lyub4i** [knudorm8/knudorm8_site#5]
Коли нажимаємо на іконку, то нічого не відбувається, а просто змінюється лінка.

![Image](https://github.com/knudorm8/knudorm8_site/assets/87826275/6e984b86-d369-46f8-8403-99a942ace83f)

**Comment by Fenimoure** [comment]
Головної сторінки не існує, тому відсутність реакції закономірна. Посилання на цій кнопці можна прибрати і повернути, коли ми створимо landing page.
