### ISSUE TITLE
Додати кастомний повзунок (приклад коду у середині)

### ISSUE THREAD

**Issue by Lyub4i** [knudorm8/knudorm8_site#6]
html {
  ::-webkit-scrollbar {
    width: 15px;
  }

  ::-webkit-scrollbar-track {
    background: var(--background-color);
  }

  ::-webkit-scrollbar-thumb{
    background: var(--text-color);
    border-radius: 8px;
    border: 3px solid var(--background-color);
  }
}

**Comment by Fenimoure** [comment]
Вирішено [тут](https://github.com/knudorm8/knudorm8_site/commit/c6dec47783fb73eee89ca553b3e72cf04cee9260)
